[advisories]
ignore = [
    "RUSTSEC-2023-0071",  # we do not use sqlx-MySQL -which use RSA
]

[database]
fetch = true
url = "https://github.com/RustSec/advisory-db.git"
stale = false

[yanked]
# Check for yanked crates (withdrawn from crates.io)
enabled = true

