name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # rust: [stable, beta, nightly]
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Install tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-tarpaulin --locked || true
          cargo install cargo-audit --locked || true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Check formatting
      - name: Check formatting
        run: cargo fmt -- --check

      # Build
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run tests
        run: cargo test --verbose

      # Run doc tests
      - name: Run doc tests
        run: cargo test --doc

      # Clippy
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run security audit
        if: matrix.os == 'ubuntu-latest'
        run: cargo audit